version: '3.8'

services:
  web:
    build: .
    command: gunicorn taskledger.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}

volumes:
  static_volume:
  media_volume:
